stages:
    - check
    - build-devel

variables:
    FLATPAK_MODULE: "era"

include:
    - project: "GNOME/citemplates"
      file: "templates/default-rules.yml"
    - project: "GNOME/citemplates"
      file: "flatpak/flatpak_ci_initiative.yml"
    - local: .gitlab-ci/check.yml
    - local: .gitlab-ci/flatpak-devel.yml
    - local: .gitlab-ci/android.yml
