include:
    - project: "GNOME/citemplates"
      file: "templates/default-rules.yml"
    - project: "GNOME/citemplates"
      file: "flatpak/flatpak_ci_initiative.yml"
    - project: "GNOME/citemplates"
      file: "templates/basic-release.yml"

variables:
    FLATPAK_MODULE: "era"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

.eds: &eds
    variables:
        MANIFEST_PATH: "build-aux/io.gitlab.TitouanReal.Era.Eds.Devel.json"
        APP_ID: "io.gitlab.TitouanReal.Era.Eds.Devel"
        BUNDLE: "era-eds-nightly.flatpak"

.mock: &mock
    variables:
        MANIFEST_PATH: "build-aux/io.gitlab.TitouanReal.Era.Mock.Devel.json"
        APP_ID: "io.gitlab.TitouanReal.Era.Mock.Devel"
        BUNDLE: "era-mock-nightly.flatpak"

.p2panda: &p2panda
    variables:
        MANIFEST_PATH: "build-aux/io.gitlab.TitouanReal.Era.P2panda.Devel.json"
        APP_ID: "io.gitlab.TitouanReal.Era.P2panda.Devel"
        BUNDLE: "era-p2panda-nightly.flatpak"

.flatpak-command: &flatpak-command
    image: "${RUNTIME_IMAGE}"
    interruptible: true
    tags:
        - flatpak
    script:
        - flatpak-builder --user --disable-rofiles-fuse --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
        - flatpak build-finish --share=network flatpak_app
        - echo "cd .. && ${COMMAND}" | flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}

.flatpak: &flatpak
    stage: build
    after_script:
        # Copy the metainfo file to the current directory.
        - cp flatpak_app/files/share/metainfo/*.metainfo.xml .
    artifacts:
        paths:
            - $BUNDLE
            - "repo.tar"
            - ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-logs/"
            # Add the metainfo file for the corresponding test.
            - "${APP_ID}.metainfo.xml"

stages:
    - check
    - build
    - test
    - deploy

cargo-fmt:
    <<: *flatpak-command
    stage: check
    variables:
        MANIFEST_PATH: "build-aux/io.gitlab.TitouanReal.Era.Eds.Devel.json"
        APP_ID: "io.gitlab.TitouanReal.Era.Eds.Devel"
        COMMAND: "cargo fmt"
    interruptible: true

cargo-clippy:
    <<: *flatpak-command
    stage: check
    variables:
        MANIFEST_PATH: "build-aux/io.gitlab.TitouanReal.Era.Eds.Devel.json"
        APP_ID: "io.gitlab.TitouanReal.Era.Eds.Devel"
        COMMAND: "cargo clippy -- -D warnings"
    interruptible: true

blueprint-format:
    stage: check
    image: "quay.io/gnome_infrastructure/gnome-build-meta:core-nightly"
    before_script:
        - shopt -s globstar
    script:
        - blueprint-compiler format **/*.blp
    interruptible: true

blueprint-lint:
    stage: check
    image: "quay.io/gnome_infrastructure/gnome-build-meta:core-nightly"
    when: manual
    before_script:
        - shopt -s globstar
    script:
        - blueprint-compiler lint **/*.blp
    allow_failure: true
    interruptible: true

flatpak-eds@x86_64:
    <<: [*eds, *flatpak]
    extends: ".flatpak@x86_64"

flatpak-eds@aarch64:
    <<: [*eds, *flatpak]
    extends: ".flatpak@aarch64"
    when: manual

flatpak-mock@x86_64:
    <<: [*mock, *flatpak]
    extends: ".flatpak@x86_64"

flatpak-mock@aarch64:
    <<: [*mock, *flatpak]
    extends: ".flatpak@aarch64"
    when: manual

flatpak-p2panda@x86_64:
    <<: [*p2panda, *flatpak]
    extends: ".flatpak@x86_64"

flatpak-p2panda@aarch64:
    <<: [*p2panda, *flatpak]
    extends: ".flatpak@aarch64"
    when: manual

# Validate the metainfo with Flathub's tool.
lint-metainfo:
    stage: test
    image:
        name: "ghcr.io/flathub/flatpak-builder-lint:latest"
        entrypoint: [""]
    variables:
        APP_ID: "io.gitlab.TitouanReal.Era.Eds.Devel"
        METAINFO: "${APP_ID}.metainfo.xml"
    interruptible: true
    script:
        # This tool has extra tests on top of appstreamcli and is required to pass for Flathub.
        - flatpak-builder-lint appstream ${METAINFO}
        # Test also with the pedantic and strict flags.
        - appstreamcli validate --pedantic --explain --strict ${METAINFO}
    needs: ["flatpak-eds@x86_64"]
