[package]
name = "kalendasom"
version = "0.1.0"
authors = ["Titouan Real <titouan.real@gmail.com>"]
edition = "2024"
rust-version = "1.89"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
adw = { package = "libadwaita", version = "0.8.0", features = ["v1_7"] }
clepsydre = { git = "https://gitlab.gnome.org/TitouanReal/clepsydre.git" }
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }
gio = { version = "0.21.1", features = ["v2_84"] }
glib = { version = "0.21.1", features = ["v2_84"] }
gdk = { package = "gdk4", version = "0.10.0", features = ["v4_18"] }
gtk = { package = "gtk4", version = "0.10.0", features = ["gnome_47"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
